### ISSUE TITLE
Language auto-detection

### ISSUE THREAD

**Issue by fsmaia** [OverZealous/code-highlight-linenums#1]
Hi,

First of all congratulations for implementing such a desired feature.

I noticed [here](https://github.com/wcoder/highlightjs-line-numbers.js/blob/master/src/highlightjs-line-numbers.js) that `highlight.js` is only called when the language is set.

But `highlight.js` has support for autodetection, using `highlightAuto(code)` [method](http://highlightjs.readthedocs.io/en/latest/api.html#highlightauto-value-languagesubset) instead.

The fix is really simple and I'm sending in some moments via pull request.

Thanks again!

**Comment by OverZealous** [comment]
Closed via PR #2
